package com.mediatek.dmagent;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int android_focused = 0x7f020000;
        public static final int android_normal = 0x7f020001;
        public static final int android_pressed = 0x7f020002;
        public static final int icon = 0x7f020003;
        public static final int stateimages = 0x7f020004;
        public static final int translucent_background = 0x7f020005;
    }

    public static final class id {
        public static final int mylinearlayout = 0x7f050000;
        public static final int btn01 = 0x7f050001;
        public static final int btn02 = 0x7f050002;
        public static final int btnFinishApp = 0x7f050003;
    }

    public static final class layout {
        public static final int main = 0x7f030000;
    }

    public static final class string {
        public static final int app_name = 0x7f040000;
        public static final int btn01 = 0x7f040001;
        public static final int btn02 = 0x7f040002;
        public static final int btnFinishApp = 0x7f040003;
    }
}
